version: '3.7'
services:

  my-gen-tree-backend:
    image: "my-gen-tree/backend:0.0.1"
    container_name: my-gen-tree-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default
  my-gen-tree-frontend:
    image: "my-gen-tree/frontend:0.0.1"
    container_name: my-gen-tree-frontend
    ports:
      - "3000:3000"
    links:
      - my-gen-tree-backend

