export const API_BASE_URL = process.env.REACT_APP_TREE_APP_SERVICE_URL || 'http://localhost:8080';
export const ACCESS_TOKEN = 'accessToken';
export const NAME_MIN_LENGTH = 2;
export const NAME_MAX_LENGTH = 50;
export const USERNAME_MIN_LENGTH = 2;
export const USERNAME_MAX_LENGTH = 50;
export const EMAIL_MAX_LENGTH = 50;
export const PASSWORD_MIN_LENGTH = 2;
export const PASSWORD_MAX_LENGTH = 100;