management:
  server:
    port: 9090
spring:
  datasource:
    url: ${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${DB_USER}
    password: ${DB_PASS}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
