management:
  server:
    port: 9090
spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:~/liquibase;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml