management:
  server:
    port: 9090
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    use_sql_comments: true
  profile:
    active: "local"
  datasource:
    url: jdbc:postgresql://localhost:5432/mygentreedb
    username: mygentreeuser
    password: mygentreepassword
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

