management:
  server:
    port: 9090
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpirationInMs: 604800000
minio:
  url: ${MINIO_URL}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: {MINIO_SECRET_KEY}
file:
  photoServerUrl: ${FILE_SERVER_URL}
  docServerUrl: ${FILE_SERVER_URL}
