management:
  server:
    port: 9090
#  management:
#    endpoints:
#      web:
#        exposure:
#          include: openapi, swaggerui
#
#
##.server.port=9090
#springdoc:
#  use-management-port: true
#
#
#
##springdoc.use-management-port=true
##management.endpoints.web.exposure.include=openapi, swagger-ui