export const updateRoute = "/api/v1/tree/person/update"
export const getTreeRoute = "/api/v1/tree/get"
export const getCurrentUserRoute = "/api/v1/user/me"
export const signInRoute = "/api/v1/auth/sign_in"
export const signUpRoute = "/api/v1/auth/sign_up"
export const checkUsernameAvailabilityRoute = "/api/v1/user/username_availability"
export const checkEmailAvailabilityRoute = "/api/v1/user/email_availability"
export const getTreeListRoute = "/api/v1/tree/get/list"